name: Running Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Step 1: checkout
      - name: Install Python  # Step 2: set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies # Step 3: install pytest, pytest-cov, flake8
        run: pip install pytest pytest-cov flake8
      - name: run pytest # Step 4: run pytest with coverage enforcement
        run: pytest --cov=. --cov-fail-under=85
      - name: run flake8 # Step 5: run flake8
        run: flake8 .

